on: push

jobs:
  echo-input:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/github-script@latest
        with:
          script: |
            const sayHello = require('../../index.js')
            const sayBye = require('../../index.js')
            sayBye()
            sayHello()